# Generated by Django 2.2 on 2019-04-20 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='username', max_length=20)),
                ('email', models.CharField(default='email', max_length=20)),
                ('password', models.CharField(default='password', max_length=20)),
                ('date', models.DateField(auto_now=True)),
            ],
        ),
    ]
