# Generated by Django 2.0.2 on 2019-01-09 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='标题', max_length=50)),
                ('tags', models.CharField(blank=True, default='文章标签', max_length=120, null=True)),
                ('abstract', models.CharField(blank=True, default='摘要', max_length=300, null=True)),
                ('content', models.TextField(default='正文')),
                ('image', models.ImageField(default='default.png', upload_to='blog_image/')),
            ],
        ),
    ]
