# Generated by Django 2.0.2 on 2019-01-22 09:10

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0005_auto_20190120_1642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='abstract',
            field=models.CharField(blank=True, default='abstract', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='content',
            field=ckeditor.fields.RichTextField(default='content'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='tags',
            field=models.CharField(blank=True, default='tag', max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='title',
            field=models.CharField(default='title', max_length=50),
        ),
    ]
