# Generated by Django 2.0.2 on 2019-01-20 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='default.png', upload_to='picture_image/')),
                ('title', models.CharField(default='标题', max_length=50)),
                ('date', models.DateTimeField()),
            ],
        ),
    ]
