# Generated by Django 2.0.2 on 2019-01-22 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('picture_app', '0002_auto_20190122_1710'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='picture',
            name='describe',
        ),
        migrations.AddField(
            model_name='picture',
            name='description',
            field=models.CharField(default='description', max_length=100),
        ),
    ]
